#0 2 * * * /root/GSIV_Telnet_Client/cron.sh
#/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Oguo > /tmp/Oguo.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Wiiz > /tmp/Wiiz.txt
#/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Bardi > /tmp/Bardi.txt
#/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Clergi > /tmp/Clergi.txt
#/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Krisalan > /tmp/Krisalan.txt
#/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Darkl > /tmp/Darkl.txt
#/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Popper > /tmp/Popper.txt
#/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Seadoo > /tmp/Seadoo.txt
#/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Zrik > /tmp/Zrik.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Woory > /tmp/Worry.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Sluf > /tmp/Sluf.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Pristeen > /tmp/Pristeen.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Itiems > /tmp/Itiems.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Itemim > /tmp/Itemim.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Loads > /tmp/Loads.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Wardrob > /tmp/Wardrob.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Loods > /tmp/Loods.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Trenus > /tmp/Trenus.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Aiss > /tmp/Aiss.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Sorci > /tmp/Sorci.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Clu > /tmp/Clu.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Monker > /tmp/Monker.txt
/root/GSIV_Telnet_Client/play_gemstoneiv_daily.pl Bize > /tmp/Bize.txt
